# Generated by Django 2.2.3 on 2019-07-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
