# Generated by Django 2.2.4 on 2019-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='picture/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
