# Generated by Django 2.2.5 on 2019-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('l', 'L'), ('fs', 'FS'), ('m', 'M'), ('xl', 'XL'), ('s', 'S')], max_length=100),
        ),
    ]
