# Generated by Django 2.2.5 on 2019-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20190918_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('xl', 'XL'), ('s', 'S'), ('fs', 'FS'), ('l', 'L'), ('m', 'M')], max_length=100),
        ),
    ]
