# Generated by Django 2.2.5 on 2019-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20190918_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default='200', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('s', 'S'), ('fs', 'FS'), ('l', 'L'), ('m', 'M'), ('xl', 'XL')], max_length=100),
        ),
    ]
